spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis


logging:
  level:
    com.market.mall: debug
