spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tBTxQ6iYQsXxuszCgT2
      secret-key: DF26SvHBUWBErGOiWlDtkq2qnES2yf
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-wyy522
  application:
    name: mall-third-party
server:
  port: 30000